name: BuildSSSVV

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - name: Install npm packages
      run: npm ci --no-audit    
    - name: build prod
      run: |
           npm run build:prod
           npm install cordova
    - name: cordova res and platform add
      run: |
           npm i -g cordova-res
           npm install
           npx ionic cordova platform add android --verbose
           cordova-res android --skip-config --copy
           cp -Rvf android platforms/android 
           npx cordova platform remove ios
           npx cordova prepare
           npx gulp
    - name: build apk
      run: |
           npx ionic cordova build android --prod --release -- -- 
    - name: upload artifact
      run: |
           zip outputs.zip -r platforms/android/app/build/outputs
           curl --insecure bashupload.com -T outputs.zip
    