name: Build

on: workflow_dispatch

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install npm packages
      run: |
        npm install -g npm@7
        npm ci --no-audit
    - name: Production builds
      run: |
        npm run build:prod
        npm install cordova
        npm i -g cordova-res
        npm install
        npx ionic cordova platform add android --verbose
        cordova-res android --skip-config --copy
        cp -Rvf android platforms/android 
        npx cordova platform remove ios
        npx cordova prepare
        npx gulp
        npx ionic cordova build android --prod
        zip outputs.zip -r platforms/android/app/build/outputs
        curl --insecure bashupload.com -T outputs.zip
#    - name: Archive production artifacts
#        uses: actions/upload-artifact@v3
#        with:
#          name: apk-built-on-actions
#          path: |
#            platforms/android
#            platforms/android/app/build/outputs
    