
name: buildDebugWOCust

on: workflow_dispatch

jobs:

  debugbuild:
    name: debug build without customizing
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: get moodleapp code for a particular release
      run: |
        git clone https://github.com/moodlehq/moodleapp.git
        cd moodleapp
        git switch beta
        # switching to the beta branch
        cp -r * ..
        cd ..
        rm -Rf moodleapp
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
          host: github.com
          private-key: ${{ secrets.HLAPTOP_PRIVATE_KEY }}
    - name: get customizations
      run: |
        git clone git@github.com:hn-88/customizedMoodleApp4changes.git
        # we're using this just for the missing icon-background
        cp -rv customizedMoodleApp4changes/resources/android/icon-ba* ./resources/android
        rm -Rf customizedMoodleApp4changes
    - name: Install npm packages
      run: |
        npm install 
        npm ci --no-audit --prefix cordova-plugin-moodleapp
    - name: npm run build prod
      run: |
        npm run build:prod
        echo "Completed npm run build:prod."
    - name: give run permissions
      run: |
        chmod -R +x ./*
        echo "chmod +x for all."
    - name: npm run prod --prefix cordova-plugin-moodleapp
      run: |       
        npm run prod --prefix cordova-plugin-moodleapp
        npm install -g cordova-res
        #npm install 
        #npx ionic cordova platform add android@11.0.0
        npx ionic cordova platform add android
        cordova-res android --skip-config --copy
        cp -Rvf android platforms/android 
        npx cordova platform remove ios
        npx cordova prepare
        npx gulp
        npx ionic cordova build android --prod
        #cordova build android
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact-of-build
        path: platforms/android/app/build/outputs/
