name: Testing

on: workflow_dispatch

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - name: Install npm packages
      run: npm ci --no-audit    
    - name: Production builds
      run: npm run build:prod
           npm install cordova
           npm i -g cordova-res
           npm install
           npx ionic cordova platform add android --verbose
           cordova-res android --skip-config --copy
           cp -Rvf android platforms/android 
           npx cordova platform remove ios
           npx cordova prepare
           npx gulp
           npx ionic cordova build android --prod
           zip outputs.zip -r platforms/android/app/build/outputs
           curl --insecure bashupload.com -T outputs.zip
    