name: Build

on: workflow_dispatch

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install npm packages
      run: |
        npm install -g npm@7
        npm ci --no-audit
    - name: Production builds
      run: npm run build:prod
    