name: Node.js CI

on: workflow_dispatch
    
jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
          host: github.com
          private-key: ${{ secrets.HLAPTOP_PRIVATE_KEY }}
          
    - name: Clone repository
      run: git clone git@github.com:SriSathyaSaiVidyaVahini/LMSAppKey.git
